apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Octapull/deephorizon.git
    targetRevision: main
    path: infra/k8s/postgresql/airflow
  destination:
    server: https://kubernetes.default.svc
    namespace: deephorizon-data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
