---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: deephorizon-data
spec:
  encryptedData:
    root-password: AgAVDbDW2BinIcXG1Tqh1rJ7odGKfDQgVy3R91qzv9Na91VDFdhlM6tEAM7AzKXye1CBCjwfu5D062kVLhPGuN6Kgy6fvCQ/WGMx+ycElYJpb+1vpQUdGvFudByZ/OAHzXSie4C/kG5jFu4NAJmCSul7vA5LBdJSpKehc3lfX9TSpo5Hl0jaKwn3FFgcgR7yniZO0IzphRFoj+EizYx2Qei0pU/mb0KMYGAfn6qNar7KcQFbkgokA0xheJtCmrsi9p7W4G3u6cP8JUNXsKimJtQjV1RjXrz0UkXtGos+tzafI4j183mXyHRhBcHKSJqcSfX4H1scoSMFebrmwggNBBSYPqph6VPPibYE/YsAbQnVG2agw1v5x5HYIPHZ9q9mjbhaAKQRjnkB2/iAJsXh0OkYGRE7AA9qW8dIuIqfkhp++nvsKGsmeIXv0Cdpw15ihsyMeEwZjAgXFfBBD3vs7tqoVOCN5+ScnI+aLqFZnYdXf90MoD/YLKq15mBHnEeooZ6Es5neHSD38vW3KBwx48dkJlywTvl/6iGIxBxYTQ0QLwrBd4rq5K+AOgwY0/bfqUaMEe8GLGtOwo97RTPuh2OvVmwmVVZf/iIITOsX59VxhtyX3iBt//6tkeNZNa62a50Y9EWMfOpo/wkqDw1FVNVAuTbxsTQ5QdfzF3DefoIvlXal9gCz+20cSyLdaF2eA4/JTqxXpkt5xOFFWwwIndx9mQpHm94gQ1V/UhGRSZK4cg==
    root-user: AgA/NsJQ4bSdhIKdXD+XlIM3KaoGChIG6KY5ymlgc/eQftSoGaYju7mjdrZhLvs1hYhHfYisfv0kwWudWm4XdlT8oq+h+ggJ1Y32E2aVXYgx9hRd4rgH5l3frFqF6V4lM6PdDpfPWT80I7QcfTbstdG7Cu9HTvfA6lqsmZCIzjuKdxb7Ze9ld3BJMxrfLMqJFg1UDvjX5XiRqkKUfuAUq8ZylmOpxdv9YkkUGZO+cIJISx986EtXNv5SvYwupKWKXsW7A62WmVnxTVhXlUa9Jof7TW6rycK4OGvcVNMiXBbh6RMI+XKHxRHS8O0wKt/p5ZAkQoOOlB5NEb88SIveGXiGu7Ww5a9ExDRdsP8lVRdNv4F3M5HOPmnzihuK1V1rYiaHm7GcxWiF40SXMxn/ax0uCgnNIg2z1ZKpUrseKPzSO4SFIyNbLlHwbcaqw6NhCfU93F0Tz7EC5al3mZYZDvAqsaM8U8NL6IXqsBOHcSh1jRku/LOBZ9pXFeHb0gl88cYN2vX+DHbXmRB2IGUfgpFS1DM1lxRkcbWInoNu2XFIzrl0XWQWeoWzrSqbJ0nbQb4/nHV3WH70rymTTRrq/Z1jsUFTp8Sn+83fuXesvM1uhGd0ixH9dyuuJPkvM/BAQm21/n1ydkjcCEMckNKWLnICUfxwwO33RJ9Z59gSmopo1SIHNzg2hfSx40PWQXuN3HPomIccUGD3uXCoIQ==
  template:
    metadata:
      name: minio-credentials
      namespace: deephorizon-data
