---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-s3-credentials
  namespace: deephorizon-ml
spec:
  encryptedData:
    access-key: AgBm66D9PIDPSJNN/Taf+cASEPhYF9I+l8JtiyxvmIiqTKVUmYcG+sS6BAvp8hsFezQENQSwGrrwwkaJlHkWe/wek7wlJbjDlqsDW0QZOmkxafJuE2JVr+k60P477qLD+zyq8ODf9lesZDBEerQt2l7Ul6BtuxyWIyRq0qU5TAwwZgf31O/J0gaDvfYqyA9YF8k47q7jbzAdCbqEjgO8SG7T9QwhAheH4VgxaYMEmWJgIlUbJ7s4/wN4AwPx5ZYQDVT5sNaLaStRRbDrdpZ/pa9PR8LgFjy8nmDFHPJYGwGRI2KYgWq2BysyIFcl7x3cUt/WJWltCRA5dit+g8IXlpNislQ5XQS6rMQf5TF1CL2qWTgrqBgJr9PjVRK9nyKq1BsFH98i4xa5AxOk/eFt7uouJ8+jY/GvUNiL+rb+sjvznUqjoyc6PwLzffwKxkNkrVoBglLfj15n1QABA/PSxGPrE+afPhgVWyM5lfgk9n6dswWGKvobFFnzkTdgnMglv5/0E3dREelmtKWj0q8G6R2OqpAXVRZLoNNIlxXdpujoVOtvCgOz2I9mPTrZsSUuKQqZyi/uLD/yLmw5tp9iT7Zy0xLeubAnt+o6PhT60236PhUoEEPJdUt+rTjSXyuncQMs3KjGP/eRQTux08cnPSE0/xv8ppFPmJFeC3biFMHfW12LnLUOmmmF0O1G1SSFmhsFBm7XcfI=
    secret-key: AgCHpaTMJyzXHXy4CuDdXNwFbNN23woMaljhZFKfr0yGlQ9MYZV8aLw4kLmNTTNzC73AD9yKSWlAYGpzqJ/43PJVQZFY4ngcivm+vHoUtuE3haqiMuFbSjrC4RGeLZZSppZ5cl7G/ZQ9Virn+PllRHhQ08VwOJ4V6mjen47D2Uoazy31aV3AkBMzVjwpJ1rtV/FNgNC9wJf/s+gb5eotCi3fzEBlNtyHgC5pvjAklGHcs4cYDnqxbWQo4gc2x/fmzbWbrlyZhwdHdLcB+QB378F/FZh0SpDPmvur1VEWg0SdQ/9QpqwekA6GdhPZS36uV7hScrmTwQABqp9Luoa1wlHzfs8zD9ujYbpS9yXhf8+y1AsS/z3k9HDQj7SQDnwvucJqBrpSHyYW3VU/vi11A78dkyIMZ4TFFSmd2/VVeX/aN0XktCA9ZgeNwf0zwbSglCsl5EuxC0gZXcLR5sqGxcB56pd2bT4uhwyfQzkTcgzHuGIvpHj0AIddnqeM0ReQoxgIJHIzBWN5VxiijYnR8h+CqliWEZkHd2TDsbnVzuTqpP5dVWPWw4exkKAv5YheH8a/VxDw8mVBWnZM9NciPAbOsQfyvNdAvv9ga7awjnqK+ept0RuTIZLEs36zmaX/yeUwjTPxJ2BrZvvQm2OgYiGUDKc3eo8o+q+LVtVkkv4y/R7lSv9LxX1+ZMIDYjvOb7pxklEfLxFLhkyOktPvEAIGfPBm7ANjn6w=
  template:
    metadata:
      name: mlflow-s3-credentials
      namespace: deephorizon-ml
