---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: deephorizon-app
spec:
  encryptedData:
    password: AgA4NDZ4Ik8fWlx9v1R1fJBVsu+4EoYlkTGU0iQ2Lkk2/iRiBZ3l0I6llt2K2PM3p7vi7Foi/7nfv+As/4H5e23Dz4MTVNXyuApkmJ9zHyuZdnVWWgHafiwvoJSrskmbbAdOgKMHcugKOd20RPXBdtSB65oo+2dnqNs2/H4/t1cy3YGjk6EGbjT3IeKPFt3FvEYpOFzmM2PLk4Oo15H1qbRMi0V0yXHJ72q8GDQ/MgWV87m8J+6KMgH2P4U2612oNXCmF/3MGIJE9EZc8+TwGO+saCz/gOKtZqqqD10FLhK421vGyb/QrYguinly8LfERgYzu8OQgbK022cPDDZlyR4NgvbQCN5ykQYAw4l1kF+HyhVnGaUChYe1cDBnYHAVfJXVqysVwghUu6XtFN+Yqou7YHPdwOZgHsfYN+UlXOdlNLgyiffjKe/jI++ivNq9W1Rte1bUM9FiAfAHapVLn7VPbKOoA2bapDm2XeJpqFI8ylmoyCHtVpbM4gMhccup6fJpOFA0BJSwHodc970EfCSR86IpVlUuJ3Sxt4mbNyGHWo27V9//QjUnFDMhVqjTg4YJJ+L794yyPl0ZT4QnegS0LyiYk3Km7Hnl63i8ZiOu2hwil+o+Vc3Jo3XOqW7GXUy/V5iOnZ89QsDzXZ2Wpp0vQDkoM0yEt93ZSTwaiiHPWBQC8iPsxoz3dzpIwbblS30nCbEUYFAqMmp+9tLnatHp8GdopEJ5FTtXFCScvzeLJ3/0KaVlCGruAGKNV/ui+sXDSBO4oSRwfrnMhEMAViPx
  template:
    metadata:
      name: redis-credentials
      namespace: deephorizon-app
