// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: deephorizon/v1/common.proto

package deephorizonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Async job lifecycle states. Sync /enhance requests jump straight to
// COMPLETED; batch requests transition QUEUED -> RUNNING -> COMPLETED.
type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_QUEUED      JobStatus = 1
	JobStatus_JOB_STATUS_RUNNING     JobStatus = 2
	JobStatus_JOB_STATUS_COMPLETED   JobStatus = 3
	JobStatus_JOB_STATUS_FAILED      JobStatus = 4
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_QUEUED",
		2: "JOB_STATUS_RUNNING",
		3: "JOB_STATUS_COMPLETED",
		4: "JOB_STATUS_FAILED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_QUEUED":      1,
		"JOB_STATUS_RUNNING":     2,
		"JOB_STATUS_COMPLETED":   3,
		"JOB_STATUS_FAILED":      4,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_deephorizon_v1_common_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_deephorizon_v1_common_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_deephorizon_v1_common_proto_rawDescGZIP(), []int{0}
}

// Raw image payload exchanged between the Go gateway and the Python
// inference server. Format is intentionally simple — the gateway is
// responsible for decoding multipart uploads into bytes.
type ImagePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`                         // raw bytes, format-aware via `mime_type`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"` // "image/png" | "image/fits" | "application/octet-stream"
	Width         uint32                 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImagePayload) Reset() {
	*x = ImagePayload{}
	mi := &file_deephorizon_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePayload) ProtoMessage() {}

func (x *ImagePayload) ProtoReflect() protoreflect.Message {
	mi := &file_deephorizon_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePayload.ProtoReflect.Descriptor instead.
func (*ImagePayload) Descriptor() ([]byte, []int) {
	return file_deephorizon_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ImagePayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ImagePayload) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ImagePayload) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImagePayload) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Image quality metrics returned alongside an enhanced image.
type Metrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Psnr            float64                `protobuf:"fixed64,1,opt,name=psnr,proto3" json:"psnr,omitempty"`
	Ssim            float64                `protobuf:"fixed64,2,opt,name=ssim,proto3" json:"ssim,omitempty"`
	Lpips           float64                `protobuf:"fixed64,3,opt,name=lpips,proto3" json:"lpips,omitempty"`
	InferenceTimeMs uint32                 `protobuf:"varint,4,opt,name=inference_time_ms,json=inferenceTimeMs,proto3" json:"inference_time_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_deephorizon_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_deephorizon_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_deephorizon_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Metrics) GetPsnr() float64 {
	if x != nil {
		return x.Psnr
	}
	return 0
}

func (x *Metrics) GetSsim() float64 {
	if x != nil {
		return x.Ssim
	}
	return 0
}

func (x *Metrics) GetLpips() float64 {
	if x != nil {
		return x.Lpips
	}
	return 0
}

func (x *Metrics) GetInferenceTimeMs() uint32 {
	if x != nil {
		return x.InferenceTimeMs
	}
	return 0
}

var File_deephorizon_v1_common_proto protoreflect.FileDescriptor

const file_deephorizon_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1bdeephorizon/v1/common.proto\x12\x0edeephorizon.v1\"m\n" +
	"\fImagePayload\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x14\n" +
	"\x05width\x18\x03 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\rR\x06height\"s\n" +
	"\aMetrics\x12\x12\n" +
	"\x04psnr\x18\x01 \x01(\x01R\x04psnr\x12\x12\n" +
	"\x04ssim\x18\x02 \x01(\x01R\x04ssim\x12\x14\n" +
	"\x05lpips\x18\x03 \x01(\x01R\x05lpips\x12*\n" +
	"\x11inference_time_ms\x18\x04 \x01(\rR\x0finferenceTimeMs*\x87\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11JOB_STATUS_QUEUED\x10\x01\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14JOB_STATUS_COMPLETED\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x04BWZUgithub.com/Octapull/deephorizon/services/api/internal/pb/deephorizon/v1;deephorizonv1b\x06proto3"

var (
	file_deephorizon_v1_common_proto_rawDescOnce sync.Once
	file_deephorizon_v1_common_proto_rawDescData []byte
)

func file_deephorizon_v1_common_proto_rawDescGZIP() []byte {
	file_deephorizon_v1_common_proto_rawDescOnce.Do(func() {
		file_deephorizon_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deephorizon_v1_common_proto_rawDesc), len(file_deephorizon_v1_common_proto_rawDesc)))
	})
	return file_deephorizon_v1_common_proto_rawDescData
}

var file_deephorizon_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_deephorizon_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_deephorizon_v1_common_proto_goTypes = []any{
	(JobStatus)(0),       // 0: deephorizon.v1.JobStatus
	(*ImagePayload)(nil), // 1: deephorizon.v1.ImagePayload
	(*Metrics)(nil),      // 2: deephorizon.v1.Metrics
}
var file_deephorizon_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_deephorizon_v1_common_proto_init() }
func file_deephorizon_v1_common_proto_init() {
	if File_deephorizon_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deephorizon_v1_common_proto_rawDesc), len(file_deephorizon_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_deephorizon_v1_common_proto_goTypes,
		DependencyIndexes: file_deephorizon_v1_common_proto_depIdxs,
		EnumInfos:         file_deephorizon_v1_common_proto_enumTypes,
		MessageInfos:      file_deephorizon_v1_common_proto_msgTypes,
	}.Build()
	File_deephorizon_v1_common_proto = out.File
	file_deephorizon_v1_common_proto_goTypes = nil
	file_deephorizon_v1_common_proto_depIdxs = nil
}
