// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: deephorizon/v1/inference.proto

package deephorizonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnhanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *ImagePayload          `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`                // e.g. "restormer-v1", "esrgan-v2"
	ScaleFactor   uint32                 `protobuf:"varint,3,opt,name=scale_factor,json=scaleFactor,proto3" json:"scale_factor,omitempty"`   // 1, 2, or 4
	OutputFormat  string                 `protobuf:"bytes,4,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"` // "png" | "fits"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnhanceRequest) Reset() {
	*x = EnhanceRequest{}
	mi := &file_deephorizon_v1_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnhanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnhanceRequest) ProtoMessage() {}

func (x *EnhanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deephorizon_v1_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnhanceRequest.ProtoReflect.Descriptor instead.
func (*EnhanceRequest) Descriptor() ([]byte, []int) {
	return file_deephorizon_v1_inference_proto_rawDescGZIP(), []int{0}
}

func (x *EnhanceRequest) GetImage() *ImagePayload {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *EnhanceRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *EnhanceRequest) GetScaleFactor() uint32 {
	if x != nil {
		return x.ScaleFactor
	}
	return 0
}

func (x *EnhanceRequest) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

type EnhanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *ImagePayload          `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Metrics       *Metrics               `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	ModelId       string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Status        JobStatus              `protobuf:"varint,4,opt,name=status,proto3,enum=deephorizon.v1.JobStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnhanceResponse) Reset() {
	*x = EnhanceResponse{}
	mi := &file_deephorizon_v1_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnhanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnhanceResponse) ProtoMessage() {}

func (x *EnhanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deephorizon_v1_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnhanceResponse.ProtoReflect.Descriptor instead.
func (*EnhanceResponse) Descriptor() ([]byte, []int) {
	return file_deephorizon_v1_inference_proto_rawDescGZIP(), []int{1}
}

func (x *EnhanceResponse) GetImage() *ImagePayload {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *EnhanceResponse) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *EnhanceResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *EnhanceResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

type EnhanceBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*EnhanceRequest      `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	MaxBatchSize  uint32                 `protobuf:"varint,2,opt,name=max_batch_size,json=maxBatchSize,proto3" json:"max_batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnhanceBatchRequest) Reset() {
	*x = EnhanceBatchRequest{}
	mi := &file_deephorizon_v1_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnhanceBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnhanceBatchRequest) ProtoMessage() {}

func (x *EnhanceBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deephorizon_v1_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnhanceBatchRequest.ProtoReflect.Descriptor instead.
func (*EnhanceBatchRequest) Descriptor() ([]byte, []int) {
	return file_deephorizon_v1_inference_proto_rawDescGZIP(), []int{2}
}

func (x *EnhanceBatchRequest) GetRequests() []*EnhanceRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *EnhanceBatchRequest) GetMaxBatchSize() uint32 {
	if x != nil {
		return x.MaxBatchSize
	}
	return 0
}

type EnhanceBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*EnhanceResponse     `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnhanceBatchResponse) Reset() {
	*x = EnhanceBatchResponse{}
	mi := &file_deephorizon_v1_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnhanceBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnhanceBatchResponse) ProtoMessage() {}

func (x *EnhanceBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deephorizon_v1_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnhanceBatchResponse.ProtoReflect.Descriptor instead.
func (*EnhanceBatchResponse) Descriptor() ([]byte, []int) {
	return file_deephorizon_v1_inference_proto_rawDescGZIP(), []int{3}
}

func (x *EnhanceBatchResponse) GetResponses() []*EnhanceResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type ModelInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                     // unique identifier
	Architecture      string                 `protobuf:"bytes,2,opt,name=architecture,proto3" json:"architecture,omitempty"` // "unet" | "pix2pix" | "esrgan" | "restormer"
	Version           string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	ValidationMetrics *Metrics               `protobuf:"bytes,4,opt,name=validation_metrics,json=validationMetrics,proto3" json:"validation_metrics,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_deephorizon_v1_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_deephorizon_v1_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_deephorizon_v1_inference_proto_rawDescGZIP(), []int{4}
}

func (x *ModelInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelInfo) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *ModelInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModelInfo) GetValidationMetrics() *Metrics {
	if x != nil {
		return x.ValidationMetrics
	}
	return nil
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_deephorizon_v1_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deephorizon_v1_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_deephorizon_v1_inference_proto_rawDescGZIP(), []int{5}
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelInfo           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_deephorizon_v1_inference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deephorizon_v1_inference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_deephorizon_v1_inference_proto_rawDescGZIP(), []int{6}
}

func (x *ListModelsResponse) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_deephorizon_v1_inference_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deephorizon_v1_inference_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_deephorizon_v1_inference_proto_rawDescGZIP(), []int{7}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	GpuAvailable  bool                   `protobuf:"varint,3,opt,name=gpu_available,json=gpuAvailable,proto3" json:"gpu_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_deephorizon_v1_inference_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deephorizon_v1_inference_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_deephorizon_v1_inference_proto_rawDescGZIP(), []int{8}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *HealthResponse) GetGpuAvailable() bool {
	if x != nil {
		return x.GpuAvailable
	}
	return false
}

var File_deephorizon_v1_inference_proto protoreflect.FileDescriptor

const file_deephorizon_v1_inference_proto_rawDesc = "" +
	"\n" +
	"\x1edeephorizon/v1/inference.proto\x12\x0edeephorizon.v1\x1a\x1bdeephorizon/v1/common.proto\"\xa7\x01\n" +
	"\x0eEnhanceRequest\x122\n" +
	"\x05image\x18\x01 \x01(\v2\x1c.deephorizon.v1.ImagePayloadR\x05image\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12!\n" +
	"\fscale_factor\x18\x03 \x01(\rR\vscaleFactor\x12#\n" +
	"\routput_format\x18\x04 \x01(\tR\foutputFormat\"\xc6\x01\n" +
	"\x0fEnhanceResponse\x122\n" +
	"\x05image\x18\x01 \x01(\v2\x1c.deephorizon.v1.ImagePayloadR\x05image\x121\n" +
	"\ametrics\x18\x02 \x01(\v2\x17.deephorizon.v1.MetricsR\ametrics\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.deephorizon.v1.JobStatusR\x06status\"w\n" +
	"\x13EnhanceBatchRequest\x12:\n" +
	"\brequests\x18\x01 \x03(\v2\x1e.deephorizon.v1.EnhanceRequestR\brequests\x12$\n" +
	"\x0emax_batch_size\x18\x02 \x01(\rR\fmaxBatchSize\"U\n" +
	"\x14EnhanceBatchResponse\x12=\n" +
	"\tresponses\x18\x01 \x03(\v2\x1f.deephorizon.v1.EnhanceResponseR\tresponses\"\xa1\x01\n" +
	"\tModelInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\farchitecture\x18\x02 \x01(\tR\farchitecture\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12F\n" +
	"\x12validation_metrics\x18\x04 \x01(\v2\x17.deephorizon.v1.MetricsR\x11validationMetrics\"\x13\n" +
	"\x11ListModelsRequest\"G\n" +
	"\x12ListModelsResponse\x121\n" +
	"\x06models\x18\x01 \x03(\v2\x19.deephorizon.v1.ModelInfoR\x06models\"\x0f\n" +
	"\rHealthRequest\"]\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12#\n" +
	"\rgpu_available\x18\x03 \x01(\bR\fgpuAvailable2\xd7\x02\n" +
	"\x10InferenceService\x12J\n" +
	"\aEnhance\x12\x1e.deephorizon.v1.EnhanceRequest\x1a\x1f.deephorizon.v1.EnhanceResponse\x12Y\n" +
	"\fEnhanceBatch\x12#.deephorizon.v1.EnhanceBatchRequest\x1a$.deephorizon.v1.EnhanceBatchResponse\x12S\n" +
	"\n" +
	"ListModels\x12!.deephorizon.v1.ListModelsRequest\x1a\".deephorizon.v1.ListModelsResponse\x12G\n" +
	"\x06Health\x12\x1d.deephorizon.v1.HealthRequest\x1a\x1e.deephorizon.v1.HealthResponseBWZUgithub.com/Octapull/deephorizon/services/api/internal/pb/deephorizon/v1;deephorizonv1b\x06proto3"

var (
	file_deephorizon_v1_inference_proto_rawDescOnce sync.Once
	file_deephorizon_v1_inference_proto_rawDescData []byte
)

func file_deephorizon_v1_inference_proto_rawDescGZIP() []byte {
	file_deephorizon_v1_inference_proto_rawDescOnce.Do(func() {
		file_deephorizon_v1_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deephorizon_v1_inference_proto_rawDesc), len(file_deephorizon_v1_inference_proto_rawDesc)))
	})
	return file_deephorizon_v1_inference_proto_rawDescData
}

var file_deephorizon_v1_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_deephorizon_v1_inference_proto_goTypes = []any{
	(*EnhanceRequest)(nil),       // 0: deephorizon.v1.EnhanceRequest
	(*EnhanceResponse)(nil),      // 1: deephorizon.v1.EnhanceResponse
	(*EnhanceBatchRequest)(nil),  // 2: deephorizon.v1.EnhanceBatchRequest
	(*EnhanceBatchResponse)(nil), // 3: deephorizon.v1.EnhanceBatchResponse
	(*ModelInfo)(nil),            // 4: deephorizon.v1.ModelInfo
	(*ListModelsRequest)(nil),    // 5: deephorizon.v1.ListModelsRequest
	(*ListModelsResponse)(nil),   // 6: deephorizon.v1.ListModelsResponse
	(*HealthRequest)(nil),        // 7: deephorizon.v1.HealthRequest
	(*HealthResponse)(nil),       // 8: deephorizon.v1.HealthResponse
	(*ImagePayload)(nil),         // 9: deephorizon.v1.ImagePayload
	(*Metrics)(nil),              // 10: deephorizon.v1.Metrics
	(JobStatus)(0),               // 11: deephorizon.v1.JobStatus
}
var file_deephorizon_v1_inference_proto_depIdxs = []int32{
	9,  // 0: deephorizon.v1.EnhanceRequest.image:type_name -> deephorizon.v1.ImagePayload
	9,  // 1: deephorizon.v1.EnhanceResponse.image:type_name -> deephorizon.v1.ImagePayload
	10, // 2: deephorizon.v1.EnhanceResponse.metrics:type_name -> deephorizon.v1.Metrics
	11, // 3: deephorizon.v1.EnhanceResponse.status:type_name -> deephorizon.v1.JobStatus
	0,  // 4: deephorizon.v1.EnhanceBatchRequest.requests:type_name -> deephorizon.v1.EnhanceRequest
	1,  // 5: deephorizon.v1.EnhanceBatchResponse.responses:type_name -> deephorizon.v1.EnhanceResponse
	10, // 6: deephorizon.v1.ModelInfo.validation_metrics:type_name -> deephorizon.v1.Metrics
	4,  // 7: deephorizon.v1.ListModelsResponse.models:type_name -> deephorizon.v1.ModelInfo
	0,  // 8: deephorizon.v1.InferenceService.Enhance:input_type -> deephorizon.v1.EnhanceRequest
	2,  // 9: deephorizon.v1.InferenceService.EnhanceBatch:input_type -> deephorizon.v1.EnhanceBatchRequest
	5,  // 10: deephorizon.v1.InferenceService.ListModels:input_type -> deephorizon.v1.ListModelsRequest
	7,  // 11: deephorizon.v1.InferenceService.Health:input_type -> deephorizon.v1.HealthRequest
	1,  // 12: deephorizon.v1.InferenceService.Enhance:output_type -> deephorizon.v1.EnhanceResponse
	3,  // 13: deephorizon.v1.InferenceService.EnhanceBatch:output_type -> deephorizon.v1.EnhanceBatchResponse
	6,  // 14: deephorizon.v1.InferenceService.ListModels:output_type -> deephorizon.v1.ListModelsResponse
	8,  // 15: deephorizon.v1.InferenceService.Health:output_type -> deephorizon.v1.HealthResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_deephorizon_v1_inference_proto_init() }
func file_deephorizon_v1_inference_proto_init() {
	if File_deephorizon_v1_inference_proto != nil {
		return
	}
	file_deephorizon_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deephorizon_v1_inference_proto_rawDesc), len(file_deephorizon_v1_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deephorizon_v1_inference_proto_goTypes,
		DependencyIndexes: file_deephorizon_v1_inference_proto_depIdxs,
		MessageInfos:      file_deephorizon_v1_inference_proto_msgTypes,
	}.Build()
	File_deephorizon_v1_inference_proto = out.File
	file_deephorizon_v1_inference_proto_goTypes = nil
	file_deephorizon_v1_inference_proto_depIdxs = nil
}
