# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: deephorizon/v1/common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'deephorizon/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x64\x65\x65phorizon/v1/common.proto\x12\x0e\x64\x65\x65phorizon.v1\"N\n\x0cImagePayload\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x11\n\tmime_type\x18\x02 \x01(\t\x12\r\n\x05width\x18\x03 \x01(\r\x12\x0e\n\x06height\x18\x04 \x01(\r\"O\n\x07Metrics\x12\x0c\n\x04psnr\x18\x01 \x01(\x01\x12\x0c\n\x04ssim\x18\x02 \x01(\x01\x12\r\n\x05lpips\x18\x03 \x01(\x01\x12\x19\n\x11inference_time_ms\x18\x04 \x01(\r*\x87\x01\n\tJobStatus\x12\x1a\n\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x15\n\x11JOB_STATUS_QUEUED\x10\x01\x12\x16\n\x12JOB_STATUS_RUNNING\x10\x02\x12\x18\n\x14JOB_STATUS_COMPLETED\x10\x03\x12\x15\n\x11JOB_STATUS_FAILED\x10\x04\x42WZUgithub.com/Octapull/deephorizon/services/api/internal/pb/deephorizon/v1;deephorizonv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deephorizon.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZUgithub.com/Octapull/deephorizon/services/api/internal/pb/deephorizon/v1;deephorizonv1'
  _globals['_JOBSTATUS']._serialized_start=209
  _globals['_JOBSTATUS']._serialized_end=344
  _globals['_IMAGEPAYLOAD']._serialized_start=47
  _globals['_IMAGEPAYLOAD']._serialized_end=125
  _globals['_METRICS']._serialized_start=127
  _globals['_METRICS']._serialized_end=206
# @@protoc_insertion_point(module_scope)
