# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from deephorizon.v1 import inference_pb2 as deephorizon_dot_v1_dot_inference__pb2

GRPC_GENERATED_VERSION = "1.83.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in deephorizon/v1/inference_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class InferenceServiceStub:
    """InferenceService is the contract between the Go API gateway and the
    Python model server. All RPCs are unary; streaming is reserved for v2.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enhance = channel.unary_unary(
            "/deephorizon.v1.InferenceService/Enhance",
            request_serializer=deephorizon_dot_v1_dot_inference__pb2.EnhanceRequest.SerializeToString,
            response_deserializer=deephorizon_dot_v1_dot_inference__pb2.EnhanceResponse.FromString,
            _registered_method=True,
        )
        self.EnhanceBatch = channel.unary_unary(
            "/deephorizon.v1.InferenceService/EnhanceBatch",
            request_serializer=deephorizon_dot_v1_dot_inference__pb2.EnhanceBatchRequest.SerializeToString,
            response_deserializer=deephorizon_dot_v1_dot_inference__pb2.EnhanceBatchResponse.FromString,
            _registered_method=True,
        )
        self.ListModels = channel.unary_unary(
            "/deephorizon.v1.InferenceService/ListModels",
            request_serializer=deephorizon_dot_v1_dot_inference__pb2.ListModelsRequest.SerializeToString,
            response_deserializer=deephorizon_dot_v1_dot_inference__pb2.ListModelsResponse.FromString,
            _registered_method=True,
        )
        self.Health = channel.unary_unary(
            "/deephorizon.v1.InferenceService/Health",
            request_serializer=deephorizon_dot_v1_dot_inference__pb2.HealthRequest.SerializeToString,
            response_deserializer=deephorizon_dot_v1_dot_inference__pb2.HealthResponse.FromString,
            _registered_method=True,
        )


class InferenceServiceServicer:
    """InferenceService is the contract between the Go API gateway and the
    Python model server. All RPCs are unary; streaming is reserved for v2.
    """

    def Enhance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def EnhanceBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Enhance": grpc.unary_unary_rpc_method_handler(
            servicer.Enhance,
            request_deserializer=deephorizon_dot_v1_dot_inference__pb2.EnhanceRequest.FromString,
            response_serializer=deephorizon_dot_v1_dot_inference__pb2.EnhanceResponse.SerializeToString,
        ),
        "EnhanceBatch": grpc.unary_unary_rpc_method_handler(
            servicer.EnhanceBatch,
            request_deserializer=deephorizon_dot_v1_dot_inference__pb2.EnhanceBatchRequest.FromString,
            response_serializer=deephorizon_dot_v1_dot_inference__pb2.EnhanceBatchResponse.SerializeToString,
        ),
        "ListModels": grpc.unary_unary_rpc_method_handler(
            servicer.ListModels,
            request_deserializer=deephorizon_dot_v1_dot_inference__pb2.ListModelsRequest.FromString,
            response_serializer=deephorizon_dot_v1_dot_inference__pb2.ListModelsResponse.SerializeToString,
        ),
        "Health": grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=deephorizon_dot_v1_dot_inference__pb2.HealthRequest.FromString,
            response_serializer=deephorizon_dot_v1_dot_inference__pb2.HealthResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "deephorizon.v1.InferenceService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "deephorizon.v1.InferenceService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class InferenceService:
    """InferenceService is the contract between the Go API gateway and the
    Python model server. All RPCs are unary; streaming is reserved for v2.
    """

    @staticmethod
    def Enhance(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/deephorizon.v1.InferenceService/Enhance",
            deephorizon_dot_v1_dot_inference__pb2.EnhanceRequest.SerializeToString,
            deephorizon_dot_v1_dot_inference__pb2.EnhanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def EnhanceBatch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/deephorizon.v1.InferenceService/EnhanceBatch",
            deephorizon_dot_v1_dot_inference__pb2.EnhanceBatchRequest.SerializeToString,
            deephorizon_dot_v1_dot_inference__pb2.EnhanceBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListModels(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/deephorizon.v1.InferenceService/ListModels",
            deephorizon_dot_v1_dot_inference__pb2.ListModelsRequest.SerializeToString,
            deephorizon_dot_v1_dot_inference__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Health(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/deephorizon.v1.InferenceService/Health",
            deephorizon_dot_v1_dot_inference__pb2.HealthRequest.SerializeToString,
            deephorizon_dot_v1_dot_inference__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
