# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: deephorizon/v1/inference.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'deephorizon/v1/inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from deephorizon.v1 import common_pb2 as deephorizon_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x64\x65\x65phorizon/v1/inference.proto\x12\x0e\x64\x65\x65phorizon.v1\x1a\x1b\x64\x65\x65phorizon/v1/common.proto\"|\n\x0e\x45nhanceRequest\x12+\n\x05image\x18\x01 \x01(\x0b\x32\x1c.deephorizon.v1.ImagePayload\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x14\n\x0cscale_factor\x18\x03 \x01(\r\x12\x15\n\routput_format\x18\x04 \x01(\t\"\xa5\x01\n\x0f\x45nhanceResponse\x12+\n\x05image\x18\x01 \x01(\x0b\x32\x1c.deephorizon.v1.ImagePayload\x12(\n\x07metrics\x18\x02 \x01(\x0b\x32\x17.deephorizon.v1.Metrics\x12\x10\n\x08model_id\x18\x03 \x01(\t\x12)\n\x06status\x18\x04 \x01(\x0e\x32\x19.deephorizon.v1.JobStatus\"_\n\x13\x45nhanceBatchRequest\x12\x30\n\x08requests\x18\x01 \x03(\x0b\x32\x1e.deephorizon.v1.EnhanceRequest\x12\x16\n\x0emax_batch_size\x18\x02 \x01(\r\"J\n\x14\x45nhanceBatchResponse\x12\x32\n\tresponses\x18\x01 \x03(\x0b\x32\x1f.deephorizon.v1.EnhanceResponse\"s\n\tModelInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x61rchitecture\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x33\n\x12validation_metrics\x18\x04 \x01(\x0b\x32\x17.deephorizon.v1.Metrics\"\x13\n\x11ListModelsRequest\"?\n\x12ListModelsResponse\x12)\n\x06models\x18\x01 \x03(\x0b\x32\x19.deephorizon.v1.ModelInfo\"\x0f\n\rHealthRequest\"C\n\x0eHealthResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t\x12\x15\n\rgpu_available\x18\x03 \x01(\x08\x32\xd7\x02\n\x10InferenceService\x12J\n\x07\x45nhance\x12\x1e.deephorizon.v1.EnhanceRequest\x1a\x1f.deephorizon.v1.EnhanceResponse\x12Y\n\x0c\x45nhanceBatch\x12#.deephorizon.v1.EnhanceBatchRequest\x1a$.deephorizon.v1.EnhanceBatchResponse\x12S\n\nListModels\x12!.deephorizon.v1.ListModelsRequest\x1a\".deephorizon.v1.ListModelsResponse\x12G\n\x06Health\x12\x1d.deephorizon.v1.HealthRequest\x1a\x1e.deephorizon.v1.HealthResponseBWZUgithub.com/Octapull/deephorizon/services/api/internal/pb/deephorizon/v1;deephorizonv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deephorizon.v1.inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZUgithub.com/Octapull/deephorizon/services/api/internal/pb/deephorizon/v1;deephorizonv1'
  _globals['_ENHANCEREQUEST']._serialized_start=79
  _globals['_ENHANCEREQUEST']._serialized_end=203
  _globals['_ENHANCERESPONSE']._serialized_start=206
  _globals['_ENHANCERESPONSE']._serialized_end=371
  _globals['_ENHANCEBATCHREQUEST']._serialized_start=373
  _globals['_ENHANCEBATCHREQUEST']._serialized_end=468
  _globals['_ENHANCEBATCHRESPONSE']._serialized_start=470
  _globals['_ENHANCEBATCHRESPONSE']._serialized_end=544
  _globals['_MODELINFO']._serialized_start=546
  _globals['_MODELINFO']._serialized_end=661
  _globals['_LISTMODELSREQUEST']._serialized_start=663
  _globals['_LISTMODELSREQUEST']._serialized_end=682
  _globals['_LISTMODELSRESPONSE']._serialized_start=684
  _globals['_LISTMODELSRESPONSE']._serialized_end=747
  _globals['_HEALTHREQUEST']._serialized_start=749
  _globals['_HEALTHREQUEST']._serialized_end=764
  _globals['_HEALTHRESPONSE']._serialized_start=766
  _globals['_HEALTHRESPONSE']._serialized_end=833
  _globals['_INFERENCESERVICE']._serialized_start=836
  _globals['_INFERENCESERVICE']._serialized_end=1179
# @@protoc_insertion_point(module_scope)
